#!/bin/bash

avr-gcc -Os -DF_CPU=16000000UL -mmcu=atmega328p -c src/serial.c -o obj/serial.o
avr-gcc -mmcu=atmega328p obj/serial.o -o bin/serial
avr-objcopy -O ihex -R .eeprom bin/serial bin/serial.hex